---
# vim:et:ts=2:ft=ansible

- name: Copy transparent hugepage setup systemd service unit
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    mode: "0644"
  loop:
    - etc/systemd/system/transparent-hugepage-setup.service
