---
# vim:et:ts=2:ft=ansible

- name: Create transparent hugepage tmpfiles config
  ansible.builtin.template:
    src: "etc/tmpfiles.d/transparent_hugepage_setup.conf.j2"
    dest: "/etc/tmpfiles.d/transparent_hugepage_setup.conf"
    owner: root
    group: root
    mode: "0644"
